database:
  host: 47.100.239.204
  port: 5432
  name: yangyu
  user: yangyu
  pass: yangyu123
  type: postgres

jpsrv:
  listen_addr: ":8081"
  log_dir: ""
  log_level: "DEBUG"
  self_addr: "http://39.98.58.238:8081"
  pri_key: "bf12996feeaa2977b6ca0d33a0e8bd2ccfc4844c6f8a7e6d15c099f8da4a255c"
  jadepool_appid: "app"
usersrv:
  listen_addr: ":8181"
  log_dir: ""
  log_level: "DEBUG"
  jpsrv_url: "http://39.98.58.238:8081"
adminsrv:
  listen_addr: ":8082"
  log_dir: ""
  log_level: "DEBUG"
cybsrv:
  log_dir: ""
  log_level: "DEBUG"
  node: "wss://hangzhou.51nebula.com/"
  blockBegin: 1848952
  gatewayAccount: "yangyutest1"
  passwordType: "config"
  gatewayPassword: "P5HuDhKrZsxeB3LPio8c8Kv3XNhh4cqnWj8dwnDTYordR"
  seedServer: "http://127.0.0.1:8899"
  seedCMDKEY: "0efee2b9b23f5337fd4b39621e55e0c12f6d7430bde05026db6d19d4b6853de0"
  coldAccount: "yangyutest12"
  gatewayPrefix: "withdraw:CybexGatewayDev"
ordersrv:
  log_dir: ""
  log_level: "DEBUG"