
jpsrv:
  listen_addr: ":8081"
  log_dir: ""
  log_level: "DEBUG"
  self_addr: "http://39.98.58.238:8081"
  pri_key: "bf12996feeaa2977b6ca0d33a0e8bd2ccfc4844c6f8a7e6d15c099f8da4a255c"
  jadepool_appid: "app"
usersrv:
  listen_addr: ":8181"
  log_dir: ""
  log_level: "DEBUG"
  jpsrv_url: "http://39.98.58.238:8081"
adminsrv:
  listen_addr: ":8082"
  log_dir: ""
  log_level: "DEBUG"

cybsrv:
  node: "wss://shanghai.51nebula.com/"
  blockBegin: 10282099
  gatewayAccount: "yangyu123"
  gatewayPassword: "P5KNfAPu82LyAuJeD7NwgggWJvqZ9UREUpXQCwCNdGp8z"
  coldAccount: "yangyu2"
  gatewayPrefix: "withdraw:CybexGateway"